App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', create_user, name='signup'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-info/', userInfo, name='userInfo'),
    path('change-info/<pk>/', changeInfo, name='changeInfo'),
]

App_Teacher/urls.py
from django.urls import path
from App_Teacher.views import *

app_name = 'App_Teacher'

urlpatterns = [
    path('write-article/<pk>/', artcle_write, name='artcle_write'),
    path('delete-article/<pk>/', delete_aritcle, name='delete_aritcle'),
    path('liked-article/<pk>/', liked_article, name='liked_article'),
    path('articles/', articles, name='articles'),
    path('quiz/', quiz, name='quiz'),
    path('quiz-edit/<pk>/', quiz_edit, name='quiz_edit'),
    path('quiz-delete/<pk>/', quiz_delete, name='quiz_delete'),
    path('comment-edit/<pk>/', comment_edit, name='comment_edit'),
    path('comment-delete/<pk>/', comment_delete, name='comment_delete'),
    path('reply-edit/<pk>/', reply_edit, name='reply_edit'),
    path('reply-delete/<pk>/', reply_delete, name='reply_delete'),
]

E_Learning/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('App_Auth.urls')),
    path('student/', include('App_Student.urls')),
    path('teacher/', include('App_Teacher.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Teacher/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='articles', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-updated_at', '-created_at', 'title']
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['-updated_at', '-created_at',]

class Replay(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    replay = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.replay
    class Meta:
        ordering = [ 'created_at', 'updated_at',]
        verbose_name_plural = 'Replies'
        
class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at',]
        
        
class Quiz(models.Model):
    answer_list= [
        ('', 'Select Correct Answer'),
        ('option_1', '(A)'),
        ('option_2', '(B)'),
        ('option_3', '(C)'),
        ('option_4', '(D)'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.TextField(max_length=500)
    option_1 = models.CharField(max_length=100)
    option_2 = models.CharField(max_length=100)
    option_3 = models.CharField(max_length=100)
    option_4 = models.CharField(max_length=100)
    answer = models.CharField(max_length=15, choices=answer_list)
    
    start_on = models.DateTimeField()
    end_on = models.DateTimeField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.question
    class Meta:
        ordering = ['-updated_at', '-created_at', 'question']
    

class AnswerList(models.Model):
    answer_list= [
        ('', 'Select Correct Answer'),
        ('option_1', '(A)'),
        ('option_2', '(B)'),
        ('option_3', '(C)'),
        ('option_4', '(D)'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    answer = models.CharField(max_length=15, choices=answer_list)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.answer

App_Teacher/forms.py
from django import forms
from django.contrib.auth.models import User
from App_Teacher.models import *



class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('user',)
        labels = {
            'title': '',
            'content': '',
            'image': '',
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter article title',  'class':"post-title-input"}),
            'content': forms.Textarea(attrs={'placeholder': 'Enter article title',  'class':"post-area"}),
        }
        
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write a comment'}),
        }
        
        
class replayFrom(forms.ModelForm):
    class Meta:
        model = Replay
        fields = ('replay',)
        labels = {
            'replay': '',
        }
        widgets = {
            'replay': forms.Textarea(attrs={'placeholder': 'Replay in this comment'}),
        }
        

    
class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('question', 'option_1', 'option_2', 'option_3', 'option_4', 'answer', 'start_on', 'end_on')
        labels = {
            '': '',
        }
        widgets = {
            'start_on': forms.TextInput(attrs={'type': 'datetime-local',}),
            'end_on': forms.TextInput(attrs={'type': 'datetime-local',}),
        }
        
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = AnswerList
        fields = ('answer',)

App_Teacher/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from App_Teacher.forms import *
from App_Auth.models import UserProfile

from django.utils import timezone
from datetime import datetime
# Create your views here.
@login_required
def artcle_write(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    if not request.user.user_profile.role == 'teacher':
        messages.warning(request,"Only Teacher Can Access This Page!")
        return redirect('home')
    article = Article.objects.get(pk=pk, user=request.user)
    print(article.image)
    form = ArticleForm(instance=article)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request,"Article Updated Successfully!")
            return redirect('home')
    return render(request, 'App_Teacher/write_article.html',context={'form': form, 'image': article.image})


@login_required
def delete_aritcle(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    if not request.user.user_profile.role == 'teacher':
        messages.warning(request,"Only Teacher Can Access This Page!")
        return redirect('home')
    article = Article.objects.get(pk=pk, user=request.user)
    article.delete()
    messages.warning(request,"Article Deleted!")
    return redirect('home')

@login_required
def articles(request):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    articles = Article.objects.all()
    commentForm = CommentForm()
    replayForm = replayFrom()
    postForm = ArticleForm()
    if request.method == 'POST':
        if 'post_article' in request.POST:
            if not request.user.user_profile.role == 'teacher':
                messages.warning(request,"Only Teacher Can Access This Page!")
                return redirect('home')
            postForm = ArticleForm(request.POST, request.FILES)
            if postForm.is_valid():
                data = postForm.save(commit=False)
                data.user = request.user
                data.save()
                messages.success(request,"Article Posted Successfully!")
                return redirect('home')
        else:
            commentForm = CommentForm(request.POST)
            replayForm= replayFrom(request.POST)
            if commentForm.is_valid():
                data = commentForm.save(commit=False)
                data.user = request.user
                pk = int(request.POST.get('article_id'))
                article = Article.objects.get(pk=pk)
                data.article = article
                data.save()
                messages.info(request,"Comment Submitted!")
                return redirect('home')
            if replayForm.is_valid():
                data = replayForm.save(commit=False)
                article_id = int(request.POST.get('article_id'))
                comment_id = int(request.POST.get('comment_id'))
                article = Article.objects.get(pk=article_id)
                comment = Comment.objects.get(pk=comment_id)
                data.user = request.user
                data.article = article
                data.comment = comment
                messages.info(request,"Reply Submitted!")
                data.save()
                return redirect('home')
        
    return render(request, 'App_Teacher/articles.html', context={'articles': articles, 'commentForm': commentForm, 'replayForm': replayForm, "postForm": postForm})


@login_required
def liked_article(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    article = Article.objects.get(pk=pk)
    is_liked = Likes.objects.filter(user=request.user, article=article)
    if is_liked.exists():
        is_liked.delete()
        messages.warning(request,"Unliked!")
    else:
        Likes.objects.create(user=request.user, article=article)
        messages.success(request,"Liked!")
    return redirect('home')


@login_required
def quiz(request):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    quizzes = Quiz.objects.all()
    filtered_quiz = []
    if request.user.user_profile.role == 'teacher':
        filtered_quiz = list(quizzes)
    else:
        for quiz in quizzes:
            date_time_start = datetime.strptime(str(quiz.start_on), '%Y-%m-%d %H:%M:%S%z')
            date_time_end = datetime.strptime(str(quiz.end_on), '%Y-%m-%d %H:%M:%S%z')
            answer = AnswerList.objects.filter(quiz=quiz, user=request.user)
            if not answer and date_time_start <= timezone.now():
                if date_time_end > timezone.now():
                    filtered_quiz.append(quiz)
    form = QuizForm()
    answerForm = AnswerForm()
    if request.method == 'POST':
        if 'quiz_answer_quiz' in request.POST:
            answerForm = AnswerForm(request.POST)
            if answerForm.is_valid():
                data = answerForm.save(commit=False)
                quiz = int(request.POST.get('quiz_id'))
                quiz = Quiz.objects.get(pk=quiz)
                already_answer = AnswerList.objects.filter(quiz=quiz, user=request.user)
                if already_answer:
                    messages.warning(request, "Answer Already Submitted")
                    return redirect('App_Teacher:quiz')
                date_time_end = datetime.strptime(str(quiz.end_on), '%Y-%m-%d %H:%M:%S%z')
                if date_time_end < timezone.now():
                    messages.warning(request, "Time is up!")
                    return redirect('App_Teacher:quiz')
                data.user = request.user
                data.quiz = quiz
                data.save()
                messages.success(request,"Answer Submitted!")
                return redirect('App_Teacher:quiz')
        form = QuizForm(request.POST)
        if form.is_valid():
            if not request.user.user_profile.role == 'teacher':
                messages.warning(request,"Only Teacher Can Access This Page!")
                return redirect('home')
            data = form.save(commit=False)
            data.user = request.user
            data.save()
            messages.success(request,"Quiz Added!")
            return redirect('App_Teacher:quiz')
    return render(request, 'App_Teacher/quiz.html', context={'quizzes': filtered_quiz, 'form': form, 'answerForm': answerForm})


@login_required
def quiz_edit(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    if not request.user.user_profile.role == 'teacher':
        messages.warning(request,"Only Teacher Can Access This Page!")
        return redirect('home')
    title = "Quiz"
    quiz = Quiz.objects.get(pk=pk, user=request.user)
    form = QuizForm(instance=quiz)
    if request.method == 'POST':
        form = QuizForm(request.POST, instance=quiz)
        if form.is_valid():
            form.save()
            messages.success(request,"Quiz Updated!")
            return redirect('App_Teacher:quiz')
    return render(request, 'App_Teacher/quiz_edit.html', context={'form': form, 'title': title})

@login_required
def quiz_delete(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    if not request.user.user_profile.role == 'teacher':
        messages.warning(request,"Only Teacher Can Access This Page!")
        return redirect('home')
    quiz = Quiz.objects.get(pk=pk, user=request.user)
    messages.warning(request,"Quiz Deleted!")
    quiz.delete()
    return redirect('App_Teacher:quiz')


@login_required
def comment_edit(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    title = "Comment"
    comment = Comment.objects.get(pk=pk, user=request.user)
    form = CommentForm(instance=comment)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            messages.info(request,"Comment Updated!")
            return redirect('home')
    return render(request, 'App_Teacher/quiz_edit.html', context={'form': form, 'title': title})

@login_required
def comment_delete(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    comment = Comment.objects.get(pk=pk, user=request.user)
    comment.delete()
    messages.warning(request,"Comment Deleted!")
    return redirect('home')

@login_required
def reply_edit(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    title = "Comment"
    comment = Replay.objects.get(pk=pk, user=request.user)
    form = replayFrom(instance=comment)
    if request.method == 'POST':

templates/App_Teacher/articles.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
ABS E-Learning {% endblock %} {% block body_block %}
{%if user.user_profile.role == 'teacher'%}
  <h3 class="text-center">Write A Article</h3>
  <form class="write-article" method="POST" enctype="multipart/form-data">
    {{postForm|crispy }}
    <label class="image-upload" for="id_image" ><i class="fa-solid fa-image fa-2x"></i></label>
    {%csrf_token%}
    <button name="post_article" type="submit" class="btn btn-primary post-btn">Post</button>
  </form>
{%endif%}
<h1 class="text-center mt-3" style="text-decoration: underline;">Articles</h1>
{%if articles|length == 0%}<h4 class='text-center mt-4' style="opacity: 0.6;">No Articles To Show</h4>{%endif%}
{%for article in articles%}
<!-- Modal -->
<div class="modal fade" id="delete{{article.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Are You Sure To Delete This Article?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a type="button" class="btn btn-danger" href="{%url 'App_Teacher:delete_aritcle' pk=article.pk%}">Delete</a>
      </div>
    </div>
  </div>
</div>
<div class="article">
  <div class="article-user">
    <img class="article-profile-image" src="/media/{{article.user.user_profile.image}}" />
    <div class="article-user-details">
      <h5>{{article.user.user_profile.name}} {%if article.user.user_profile.role == 'teacher'%}<span class="text-info">( Teacher )</span>{%endif%}</h5>
      <p>Post on: {{article.created_at}}</p>
    </div>
    {%if user == article.user%}
    <div class="post-menu">
      <i class="fa-solid fa-ellipsis-vertical fa-2x"></i>
      <div class="menus">
        <a class="btn btn-sm btn-warning w-100 m-1" href="{%url 'App_Teacher:artcle_write' pk=article.pk%}">Edit Post</a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger btn-sm w-100 m-1" data-toggle="modal" data-target="#delete{{article.id}}">
          Delete Post
        </button>
      </div>
    </div>
    {%endif%}
  </div>
  <h4 style="align-self: center;">{{article.title}}</h4>
  <div class="short-post" onclick="maximizePost(this)">
    {{article.content|linebreaks|slice:200}}
    {%if article.content|length >= 200%}.....{%endif%}
  </div>
  <div class="full-post" onclick="minimizePost(this)" style="display: none;">{{article.content|linebreaks}}</div>
  {%if article.content|length >= 200%}
  <div class="d-flex w-100 mb-2">
    <span class="ml-auto see-more-btn" onclick="postFullShort(this)">See More...</span>
  </div>
  {%endif%}
  {%if article.image%}
  <div class="article-image">
    <img src="/media/{{article.image}}" />
  </div>
  {%endif%}
  <div class="like-comment-bar">
    <div>{{article.likes.all.count}}<a href="{%url 'App_Teacher:liked_article' pk=article.pk%}" class="ml-2 btn-like-comment is-liked">
      {%for like in article.likes.all%}
      {%if like.user == user%}
      <i class="fa-solid fa-heart"></i>
      {%endif%}
      {%endfor%}
    </a></div>
    <span
      type="button"
      class="btn-like-comment"
      data-toggle="modal"
      data-target="#article{{article.id}}"
    >
      Comment
    </span>
  </div>
  <!-- Modal -->
  <div
    class="modal fade"
    id="article{{article.id}}"
    tabindex="-1"
    role="dialog"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-dark">
          <h5 class="modal-title" id="exampleModalLabel">
            Comments<span class="count">{{article.comments.all.count}}</span>
          </h5>
          <button
            type="button"
            class="close text-light"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body bg-dark">
          {%for comment in article.comments.all%}
          <div class="modal fade" id="deletecomment{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title text-dark" id="exampleModalLabel">Are You Sure To Delete This Comment?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <a type="button" class="btn btn-danger" href="{%url 'App_Teacher:comment_delete' pk=comment.pk%}">Delete</a>
                </div>
              </div>
            </div>
          </div>
          <div class="comment">
            <div class="comment-user">
              <img class="article-profile-image" src="/media/{{comment.user.user_profile.image}}" />
              <div class="article-user-details w-100">
                <div class='w-100 d-flex'>
                  <h5>{{comment.user.user_profile.name}} {%if comment.user.user_profile.role == 'teacher'%}<span class="text-info">( Teacher )</span>{%endif%}</h5>
                  {%if user == comment.user%}
                  <div class="post-menu" style="justify-self: flex-end;">
                    <i class="fa-solid fa-ellipsis-vertical"></i>
                    <div class="com-rep-menu" style="right: 2px;">
                      <a class="btn btn-sm btn-warning w-100 m-1" href="{%url 'App_Teacher:comment_edit' pk=comment.pk%}">Edit Comment</a>
                      <!-- Button trigger modal -->
                      <button type="button" class="btn btn-danger btn-sm w-100 m-1" data-toggle="modal" data-target="#deletecomment{{comment.id}}">
                        Delete Comment
                      </button>
                    </div>
                  </div>
                  {%endif%}
                </div>
                <div class="short-post" onclick="maximizePost(this)">
                  {{comment.content|linebreaks|slice:80}}
                  {%if comment.content|length >= 80%}.....{%endif%}
                </div>
                <div class="full-post" onclick="minimizePost(this)" style="display: none;">{{comment.content|linebreaks}}</div>
                {%if comment.content|length >= 80%}
                <div class="d-flex w-100 mb-2">
                  <span class="ml-auto text-info see-more-btn" onclick="postFullShort(this)">See More...</span>
                </div>
                {%endif%}
              </div>
            </div>
            <div style="display: flex; width: 100%;">
              <span class="ml-auto mr-2" style="cursor: pointer; color: tomato;" onclick="showTextarea(this)">
                Reply
              </span>
              <span style="opacity: 0.6;">{{comment.replies.all|length}}</span>
            </div>
            <div class="pl-4 w-100" style="display: none;">
              {%for replay in comment.replies.all%}
              <div class="modal fade" id="deletereply{{replay.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title text-dark" id="exampleModalLabel">Are You Sure To Delete This Reply?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <a type="button" class="btn btn-danger" href="{%url 'App_Teacher:reply_delete' pk=replay.pk%}">Delete</a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="comment-user">
                <img class="comment-profile-image" src="/media/{{replay.user.user_profile.image}}" />
                <div class="article-user-details w-100">
                  <div class='w-100 d-flex'>
                    <h6>{{replay.user.user_profile.name}} {%if replay.user.user_profile.role == 'teacher'%}<span class="text-info">( Teacher )</span>{%endif%}</h6>
                    {%if user == replay.user%}
                    <div class="post-menu" style="justify-self: flex-end;">
                      <i class="fa-solid fa-ellipsis-vertical"></i>
                      <div class="com-rep-menu" style="right: 2px;">
                        <a class="btn btn-sm btn-warning w-100 m-1" href="{%url 'App_Teacher:reply_edit' pk=replay.pk%}">Edit Reply</a>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger btn-sm w-100 m-1" data-toggle="modal" data-target="#deletereply{{replay.id}}">
                          Delete Reply
                        </button>
                      </div>
                    </div>
                    {%endif%}
                  </div>
                  <div class="short-post" onclick="maximizePost(this)">
                    {{replay.replay|linebreaks|slice:80}}
                    {%if replay.replay|length >= 80%}.....{%endif%}
                  </div>
                  <div class="full-post" onclick="minimizePost(this)" style="display: none;">{{replay.replay|linebreaks}}</div>
                  {%if replay.replay|length >= 80%}
                  <div class="d-flex w-100 mb-2">
                    <span class="ml-auto text-info see-more-btn" onclick="postFullShort(this)">See More...</span>
                  </div>
                  {%endif%}
                </div>
              </div>
              {%endfor%}
              <hr style="background: white;">
              <form method="POST" class="mt-2">
                {% csrf_token %} {{replayForm|crispy}}
                <input type="hidden" name="article_id" value="{{article.pk}}" />
                <input type="hidden" name="comment_id" value="{{comment.pk}}" />
                <input type="submit" value="Reply" class="btn btn-secondary w-100" />
              </form>
            </div>
          </div>
          {%endfor%}
          <hr style="background: white;">
          <form method="POST">
            {% csrf_token %} {{commentForm|crispy}}
            <input type="hidden" name="article_id" value="{{article.pk}}" />
            <input type="submit" value="Comment" class="btn btn-info w-100" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endfor%} {% endblock %}

templates/App_Teacher/quiz_edit.html
{% extends "base.html" %} {%load crispy_forms_tags%} {% block title_block %}Edit
{{title}}{% endblock title_block %} {% block body_block %}
<h1>Edit {{title}}</h1>
<form method="POST" class="write-article">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Update" class="btn btn-success w-100" />
</form>
{% endblock body_block %}

templates/App_Teacher/write_article.html
{% extends "base.html" %} {%load crispy_forms_tags%} {% block title_block %}Edit
article{% endblock title_block %} {% block body_block %}
<h1>Edit article</h1>
<form method="POST" enctype="multipart/form-data" class="write-article">
  {% csrf_token %}
  <label style="bottom: 40px; left: 60px;" class="image-upload" for="id_image"
    ><i class="fa-solid fa-image fa-2x"></i
  ></label>
  {{ form|crispy }}
  <input type="submit" value="Update" class="btn btn-success w-100" />
</form>
{% endblock body_block %}