App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', create_user, name='signup'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-info/', userInfo, name='userInfo'),
    path('change-info/<pk>/', changeInfo, name='changeInfo'),
]

App_Student/urls.py
from django.urls import path
from App_Student.views import *

app_name = 'App_Student'

urlpatterns = [
    path('questions/', questions, name='questions'),
    path('question-edit/<pk>/', question_edit, name='question_edit'),
    path('question-delete/<pk>/', question_delete, name='question_delete'),
    path('answer-edit/<pk>/', answer_edit, name='answer_edit'),
    path('answer-delete/<pk>/', answer_delete, name='answer_delete'),
    path('quiz-results/', quiz_results, name='quiz_results'),
]

App_Teacher/urls.py
from django.urls import path
from App_Teacher.views import *

app_name = 'App_Teacher'

urlpatterns = [
    path('write-article/<pk>/', artcle_write, name='artcle_write'),
    path('delete-article/<pk>/', delete_aritcle, name='delete_aritcle'),
    path('liked-article/<pk>/', liked_article, name='liked_article'),
    path('articles/', articles, name='articles'),
    path('quiz/', quiz, name='quiz'),
    path('quiz-edit/<pk>/', quiz_edit, name='quiz_edit'),
    path('quiz-delete/<pk>/', quiz_delete, name='quiz_delete'),
    path('comment-edit/<pk>/', comment_edit, name='comment_edit'),
    path('comment-delete/<pk>/', comment_delete, name='comment_delete'),
    path('reply-edit/<pk>/', reply_edit, name='reply_edit'),
    path('reply-delete/<pk>/', reply_delete, name='reply_delete'),
]

E_Learning/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('App_Auth.urls')),
    path('student/', include('App_Student.urls')),
    path('teacher/', include('App_Teacher.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}?{% now “U” %}" />
    <title>{% block title_block %} E-Learning {% endblock %}</title>
  </head>
  <body>
    <header>
      <nav
        class="navbar navbar-expand-lg navbar-dark"
        style="
          background-image: linear-gradient(to bottom, rgb(97, 97, 97), #000000);
          border-bottom: 1px solid black;
        "
      >
        <a class="navbar-brand" href="/">E-Learning</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link nav-item active" href="/">Home</a>
            {% if user.is_authenticated %}
            <a
              class="nav-link nav-item active notification-parent"
              href="{%url 'App_Student:questions'%}"
            >
              <i class="fas fa-question-circle"></i>
              {%if user.user_profile.role == 'teacher'%}
              <span class="notification">{{my_data.question}}</span>
              {%endif%}
            </a>
            <a
              class="nav-link nav-item active notification-parent"
              href="{%url 'App_Teacher:quiz'%}"
            >
              <i class="fas fa-lightbulb"></i>
              {%if user.user_profile.role == 'student'%}
              <span class="notification">{{my_data.quiz}}</span>
              {%endif%}
            </a>
            <div class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                @{{user.username}}
              </a>
              <div
                class="dropdown-menu shadow-lg bg-secondary"
                aria-labelledby="navbarDropdown"
                style="left: -100px"
              >
                <a
                  class="dropdown-item"
                  href="{%url 'App_Auth:changeInfo' pk=user.pk%}"
                >
                  Profile
                </a>
                <a
                  class="dropdown-item"
                  href="{%url 'App_Student:quiz_results'%}"
                >
                  Quiz Results
                </a>
                <a class="dropdown-item" href="{%url 'App_Auth:logout'%}">
                  Logout
                </a>
              </div>
            </div>
            {% else %}
            <a class="nav-link nav-item" href="{%url 'App_Auth:signup'%}"
              >Sign Up</a
            >
            <a class="nav-link nav-item" href="{%url 'App_Auth:login'%}"
              >Login</a
            >
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <div class="messages container">
      {%if messages%} {%for message in messages%}
      <div
        {%if
        message.tags%}
        class="alert alert-{{message.tags}} alert-dismissible fade show"
        {%
        endif
        %}
        role="alert"
      >
        {{message}}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {%endfor%} {%endif%}
    </div>
    <div class="container pt-4 pb-4 w-100">
      {% block body_block %} {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/index.js' %}?{% now “U” %}"></script>
  </body>
</html>