App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', create_user, name='signup'),
    path('login/', login_page, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-info/', userInfo, name='userInfo'),
    path('change-info/<pk>/', changeInfo, name='changeInfo'),
]

App_Student/urls.py
from django.urls import path
from App_Student.views import *

app_name = 'App_Student'

urlpatterns = [
    path('questions/', questions, name='questions'),
    path('question-edit/<pk>/', question_edit, name='question_edit'),
    path('question-delete/<pk>/', question_delete, name='question_delete'),
    path('answer-edit/<pk>/', answer_edit, name='answer_edit'),
    path('answer-delete/<pk>/', answer_delete, name='answer_delete'),
    path('quiz-results/', quiz_results, name='quiz_results'),
]

E_Learning/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('App_Auth.urls')),
    path('student/', include('App_Student.urls')),
    path('teacher/', include('App_Teacher.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Student/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['-updated_at', '-created_at', 'content']


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['-updated_at', '-created_at', 'content']

App_Student/forms.py
from django import forms
from django.contrib.auth.models import User

from App_Student.models import *


class QuestionFrom(forms.ModelForm):
    class Meta:
        model = Question
        fields = ("content",)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Ask a question',  'class':"post-area"}),
        }
        
        
class QuestionAnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("content",)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Answer this question'}),
        }

App_Student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from App_Student.forms import *
from App_Teacher.forms import *
from App_Auth.models import UserProfile

from django.utils import timezone
from datetime import datetime

# Create your views here.
@login_required
def questions(request):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    questionForm = QuestionFrom()
    answerForm = QuestionAnswerForm()
    if request.method == 'POST':
        questionForm = QuestionFrom(request.POST)
        answerForm = QuestionAnswerForm(request.POST)
        if 'post_question' in request.POST:
            if questionForm.is_valid():
                ques = questionForm.save(commit=False)
                ques.user = request.user
                ques.save()
                messages.info(request,"Question Added!")
                return redirect('App_Student:questions')
        else:
            if answerForm.is_valid():
                ans = answerForm.save(commit=False)
                ans.user = request.user
                pk = int(request.POST.get('question_id'))
                ques = Question.objects.get(pk=pk)
                ans.question = ques
                ans.save()
                messages.info(request,"Answer Submitted!")
                return redirect('App_Student:questions')
    questions = Question.objects.all()
    return render(request, 'App_Student/questions.html', context={"questionForm": questionForm, 'answerForm': answerForm, 'questions': questions})
    



@login_required
def question_edit(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    title = "Question"
    question = Question.objects.get(pk=pk, user=request.user)
    form = QuestionFrom(instance=question)
    if request.method == 'POST':
        form = QuestionFrom(request.POST, instance=question)
        if form.is_valid():
            form.save()
            messages.info(request,"Question Updated!")
            return redirect('App_Student:questions')
    return render(request, 'App_Teacher/quiz_edit.html', context={'form': form, 'title': title})

@login_required
def question_delete(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    question = Question.objects.get(pk=pk, user=request.user)
    question.delete()
    messages.warning(request,"Question Deleted!")
    return redirect('App_Student:questions')

@login_required
def answer_edit(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    title = "Answer"
    answre = Answer.objects.get(pk=pk, user=request.user)
    form = AnswerForm(instance=answre)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answre)
        if form.is_valid():
            form.save()
            messages.info(request,"Answer Updated!")
            return redirect('App_Student:questions')
    return render(request, 'App_Teacher/quiz_edit.html', context={'form': form, 'title': title})

@login_required
def answer_delete(request, pk):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    answer = Answer.objects.get(pk=pk, user=request.user)
    answer.delete()
    messages.warning(request,"Answer Deleted!")
    return redirect('App_Student:questions')


@login_required
def quiz_results(request):
    userinfo = UserProfile.objects.filter(user=request.user)
    if not userinfo:
        messages.warning(request,"Add your information first!")
        return redirect('App_Auth:userInfo')
    lists = []
    result_teacher = []
    if request.user.user_profile.role == 'teacher':
        answers_teacher = AnswerList.objects.all()
        for answer in answers_teacher:
            quiz = Quiz.objects.get(id=answer.quiz.id)
            result_teacher.append({"quiz": quiz, "answer": answer})
    else:
        answers = AnswerList.objects.filter(user=request.user)
        for answer in answers:
            quiz = Quiz.objects.get(id=answer.quiz.id)
            date_time_end = datetime.strptime(str(quiz.end_on), '%Y-%m-%d %H:%M:%S%z')
            if date_time_end < timezone.now():
                lists.append({"quiz": quiz, "answer": answer})
    
    return render(request, 'App_Student/quiz_results.html', context={"lists": lists, "result_teacher": result_teacher})

templates/App_Student/questions.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
QNA {% endblock %} {% block body_block %}
<h3 class="text-center">Ask a question</h3>
<form class="write-article" method="POST">
  {{questionForm|crispy }}
  {%csrf_token%}
  <button name="post_question" type="submit" class="btn btn-primary post-btn">Ask</button>
</form>
<h1 class="text-center mt-3" style="text-decoration: underline;">Questions</h1>
{%if questions|length == 0%}<h4 class='text-center mt-4' style="opacity: 0.6;">No Questions To Show</h4>{%endif%}
{%for question in questions%}
<!-- Modal -->
<div class="modal fade" id="delete{{question.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Are You Sure To Delete This Question?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a type="button" class="btn btn-danger" href="{%url 'App_Student:question_delete' pk=question.pk%}">Delete</a>
      </div>
    </div>
  </div>
</div>
<div class="article">
  <div class="article-user">
    <img class="article-profile-image" src="/media/{{question.user.user_profile.image}}" />
    <div class="article-user-details">
      <h5>{{question.user.user_profile.name}} {%if question.user.user_profile.role == 'teacher'%}<span class="text-info"><span class="text-info">( Teacher )</span></span>{%endif%}</h5>
      <p>Post on: {{question.created_at}}</p>
    </div>
    {%if user == question.user%}
    <div class="post-menu">
      <i class="fa-solid fa-ellipsis-vertical fa-2x"></i>
      <div class="menus">
        <a class="btn btn-sm btn-warning w-100 m-1" href="{%url 'App_Student:question_edit' pk=question.pk%}">Edit</a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger btn-sm w-100 m-1" data-toggle="modal" data-target="#delete{{question.id}}">
          Delete
        </button>
      </div>
    </div>
    {%endif%}
  </div>
  <h4 style="align-self: center;">{{question.title}}</h4>
  <div class="short-post" onclick="maximizePost(this)">
    {{question.content|linebreaks|slice:200}}
    {%if question.content|length >= 200%}.....{%endif%}
  </div>
  <div class="full-post" onclick="minimizePost(this)" style="display: none;">{{question.content|linebreaks}}</div>
  {%if question.content|length >= 200%}
  <div class="d-flex w-100 mb-2">
    <span class="ml-auto see-more-btn" onclick="postFullShort(this)">See More...</span>
  </div>
  {%endif%}
    <div type="button" class="btn btn-info ml-auto" 
    onclick="showAnswers(this)" >Answers</div>
  <div class="w-100 answers" style="display: none;">
    <button
    type="button"
    class="close text-light"
    data-dismiss="modal"
    aria-label="Close"
    >
    <span aria-hidden="true">&times;</span>
    </button>
    <div class="modal-body bg-dark">
        <h5 class="modal-title" id="exampleModalLabel">
        Answers<span class="count">{{question.answers.all.count}}</span>
        </h5>
        {%for answer in question.answers.all%}
        <div class="modal fade" id="deleteanswer{{answer.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-dark" id="exampleModalLabel">Are You Sure To Delete This Answer?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a type="button" class="btn btn-danger" href="{%url 'App_Student:answer_delete' pk=answer.pk%}">Delete</a>
            </div>
            </div>
        </div>
        </div>
          <div class="comment-user">
              <img class="article-profile-image" src="/media/{{answer.user.user_profile.image}}" />
              <div class="article-user-details w-100">
              <div class='w-100 d-flex'>
                  <h5>{{answer.user.user_profile.name}} {%if answer.user.user_profile.role == 'teacher'%}<span class="text-info"><span class="text-info">( Teacher )</span></span>{%endif%}</h5>
                  {%if user == answer.user%}
                  <div class="post-menu" style="justify-self: flex-end;">
                  <i class="fa-solid fa-ellipsis-vertical"></i>
                  <div class="com-rep-menu" style="right: 2px;">
                      <a class="btn btn-sm btn-warning w-100 m-1" href="{%url 'App_Student:answer_edit' pk=answer.pk%}">Edit answer</a>
                      <!-- Button trigger modal -->
                      <button type="button" class="btn btn-danger btn-sm w-100 m-1" data-toggle="modal" data-target="#deleteanswer{{answer.id}}">
                      Delete answer
                      </button>
                  </div>
                  </div>
                  {%endif%}
              </div>
              <div class="short-post" onclick="maximizePost(this)">
                  {{answer.content|linebreaks|slice:80}}
                  {%if answer.content|length >= 80%}.....{%endif%}
              </div>
              <div class="full-post" onclick="minimizePost(this)" style="display: none;">{{answer.content|linebreaks}}</div>
              {%if answer.content|length >= 80%}
              <div class="d-flex w-100 mb-2">
                  <span class="ml-auto text-info see-more-btn" onclick="postFullShort(this)">See More...</span>
              </div>
              {%endif%}
              </div>
          </div>

        {%endfor%}
        <hr style="background: white;">
        <form method="POST" class="mt-2">
        {% csrf_token %} {{answerForm|crispy}}
        <input type="hidden" name="question_id" value="{{question.pk}}" />
        <input type="submit" value="Answer" class="btn btn-info w-100" />
        </form>
    </div>
  </div>
</div>
{%endfor%} {% endblock %}

templates/App_Student/quiz_results.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
Quiz Result {% endblock %}
{% block body_block %}
<h1 class="text-center">Quiz Results</h1>
{%if user.user_profile.role == 'teacher'%}
{%if result_teacher|length == 0%}<h4 class='text-center mt-4' style="opacity: 0.6;">No Results To Show</h4>{%endif%}
{%for res in result_teacher%}
<div class="card text-dark" style="position: relative">
  <div class="card-body">
    <h3 class="card-title">Quiz: {{res.quiz}}</h3>
    <div class="quiz-time-duration">
      <span>Starting time:  {{res.quiz.start_on}}</span>
      <span>Ending time:  {{res.quiz.end_on}}</span>
    </div>
    <div class="quiz-options text-light">
      <p>A | {{res.quiz.option_1}}</p>
      <p>B | {{res.quiz.option_2}}</p>
      <p>C | {{res.quiz.option_3}}</p>
      <p>D | {{res.quiz.option_4}}</p>
    </div>
    <div class="quiz-answers">
      <p class="card-text text-primary">
        Correct Answer: {%if res.quiz.answer == "option_1"%}
        {{res.quiz.option_1}} {%elif res.quiz.answer == "option_2"%}
        {{res.quiz.option_2}} {%elif res.quiz.answer == "option_3"%}
        {{res.quiz.option_3}} {%elif res.quiz.answer == "option_4"%}
        {{res.quiz.option_4}} {%endif%}
      </p>
      <!-- Modal -->
      <div class="modal fade" id="userinfo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Student Details</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body quiz-student-info">
              <img class="student-image" src="/media/{{res.answer.user.user_profile.image}}" />
              <h3>Student Name: {{res.answer.user.user_profile.name}}</h3>
              <h5>Student Id: {{res.answer.user.user_profile.id_number}}</h5>
              <h5>Student Address: {{res.answer.user.user_profile.address}}</h5>
            </div>
          </div>
        </div>
      </div>
      <p class="card-text">
        <span style="cursor: pointer; color: tomato;" data-toggle="modal" data-target="#userinfo">{{res.answer.user.user_profile.name}}</span>'s Answer: {%if res.answer.answer == "option_1"%}
        {{res.quiz.option_1}} {%elif res.answer.answer == "option_2"%}
        {{res.quiz.option_2}} {%elif res.answer.answer == "option_3"%}
        {{res.quiz.option_3}} {%elif res.answer.answer == "option_4"%}
        {{res.quiz.option_4}} {%endif%}
      </p>
    </div>
    <div class="quiz-status">
      {%if res.answer.answer == res.quiz.answer%}
      <i class="fa-solid fa-circle-check text-success fa-2x ml-auto"></i>
      {%else%}
      <i class="fa-solid fa-circle-xmark text-danger fa-2x ml-auto"></i>
      {%endif%}
    </div>
  </div>
</div>
{%endfor%}
{%else%}
{%if lists|length == 0%}<h4 class='text-center mt-4' style="opacity: 0.6;">No Results To Show</h4>{%endif%}
{%for res in lists%}
<div class="card text-dark" style="position: relative">
  <div class="card-body">
    <h3 class="card-title">Quiz: {{res.quiz}}</h3>
    <div class="quiz-time-duration">
      <span>Starting time:  {{res.quiz.start_on}}</span>
      <span>Ending time:  {{res.quiz.end_on}}</span>
    </div>
    <div class="quiz-options text-light">
      <p>A | {{res.quiz.option_1}}</p>
      <p>B | {{res.quiz.option_2}}</p>
      <p>C | {{res.quiz.option_3}}</p>
      <p>D | {{res.quiz.option_4}}</p>
    </div>
    <div class="quiz-answers">
      <p class="card-text text-primary">
        Correct Answer: {%if res.quiz.answer == "option_1"%}
        {{res.quiz.option_1}} {%elif res.quiz.answer == "option_2"%}
        {{res.quiz.option_2}} {%elif res.quiz.answer == "option_3"%}
        {{res.quiz.option_3}} {%elif res.quiz.answer == "option_4"%}
        {{res.quiz.option_4}} {%endif%}
      </p>
      <p class="card-text">
        Your Answer: {%if res.answer.answer == "option_1"%}
        {{res.quiz.option_1}} {%elif res.answer.answer == "option_2"%}
        {{res.quiz.option_2}} {%elif res.answer.answer == "option_3"%}
        {{res.quiz.option_3}} {%elif res.answer.answer == "option_4"%}
        {{res.quiz.option_4}} {%endif%}
      </p>
    </div>
    <div class="quiz-status">
      {%if res.answer.answer == res.quiz.answer%}
      <i class="fa-solid fa-circle-check text-success fa-2x ml-auto"></i>
      {%else%}
      <i class="fa-solid fa-circle-xmark text-danger fa-2x ml-auto"></i>
      {%endif%}
    </div>
  </div>
</div>
{%endfor%}
{%endif%}
{% endblock %}